FROM rust:1.86-alpine AS builder

WORKDIR /app

# Install build dependencies for Alpine
RUN apk add --no-cache build-base

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build --release

FROM scratch AS final

WORKDIR /app

COPY --from=builder /app/target/release/qr-code-api ./qr-code-api

CMD ["./qr-code-api"]