name: qr-code-api-dev
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RUST_LOG=debug
    volumes:
      - ./src:/app/src
      - ./api:/app/api
      - ./static:/app/static
