openapi: 3.0.0
info:
  title: QR Code Generation API
  description: |
    This API provides endpoints for generating QR codes based on the input content provided in the URL path.
  version: 2.0.0
paths:
  /svg/{content}:
    get:
      tags:
        - QR Code
      summary: Generate QR Code in SVG format with the specified content
      parameters:
        - $ref: "#/components/parameters/content"
      responses:
        "200":
          description: QR code generated successfully.
          content:
            image/svg+xml:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/InvalidContent"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /png/{content}:
    get:
      tags:
        - QR Code
      summary: Generate QR Code in PNG format with the specified content
      parameters:
        - $ref: "#/components/parameters/content"
      responses:
        "200":
          description: QR code generated successfully.
          content:
            image/png:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/InvalidContent"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  parameters:
    content:
      name: content
      in: path
      required: true
      description: The content for the QR code. This can be any string, such as a URI or text.
      schema:
        type: string
        example: "https://tuukka.net"
  responses:
    InvalidContent:
      description: Invalid content provided
      content:
        text/plain:
          schema:
            type: string
            example: "Error: Content too long"
    InternalServerError:
      description: Internal server error occurred
      content:
        text/plain:
          schema:
            type: string
            example: "Error: Internal server error"
