openapi: 3.0.0
info:
  title: QR Code Generation API
  description: |
    This API provides endpoints for generating QR codes based on the input content provided in the URL path.
  version: 2.0.0
paths:
  /{format}/{content}:
    get:
      tags:
        - QR Code
      summary: Generate QR Code in the specified format with the specified content
      parameters:
        - name: format
          in: path
          required: true
          description: The image format for the QR code.
          schema:
            enum:
              - svg
              - png
        - name: content
          in: path
          required: true
          description: The content for the QR code. This can be any string, such as a URI or text.
          schema:
            type: string
            example: "https://tuukka.net"
      responses:
        "200":
          description: QR code generated successfully.
          content:
            image/*:
              schema:
                type: string
        "400":
          description: Invalid content provided
          content:
            text/plain:
              schema:
                type: string
                example: "Error: Content too long"
        "500":
          description: Internal server error occurred
          content:
            text/plain:
              schema:
                type: string
                example: "Error: Internal server error"
